type Mime = {
  names: string[];
  extension: string;
};

export class MimeUtils {
  static findExtension(mimeType: string): string | undefined {
    return mimes.find(item => {
      return !!item.names.find(name => name === mimeType);
    })?.extension;
  }
}

const mimes: Mime[] = [
  { names: ['text/apl'], extension: 'apl' },
  { names: ['application/pgp', 'application/pgp-encrypted', 'application/pgp-keys', 'application/pgp-signature'], extension: 'asc' },
  { names: ['text/x-ttcn-asn'], extension: 'asn' },
  { names: ['text/x-brainfuck'], extension: 'b' },
  { names: ['text/x-csrc'], extension: 'c' },
  { names: ['text/x-c++src'], extension: 'cpp' },
  { names: ['text/x-cobol'], extension: 'cob' },
  { names: ['text/x-csharp'], extension: 'cs' },
  { names: ['text/x-clojure'], extension: 'clj' },
  { names: ['text/x-clojurescript'], extension: 'cljs' },
  { names: ['text/x-gss'], extension: 'gss' },
  { names: ['text/x-cmake'], extension: 'cmake' },
  { names: ['application/vnd.coffeescript', 'text/coffeescript', 'text/x-coffeescript'], extension: 'coffee' },
  { names: ['text/x-common-lisp'], extension: 'cl' },
  { names: ['application/x-cypher-query'], extension: 'cyp' },
  { names: ['text/x-cython'], extension: 'pyx' },
  { names: ['text/x-crystal'], extension: 'cr' },
  { names: ['text/css'], extension: 'css' },
  { names: ['text/x-cassandra'], extension: 'cql' },
  { names: ['text/x-d'], extension: 'd' },
  { names: ['application/dart', 'text/x-dart'], extension: 'dart' },
  { names: ['text/x-diff'], extension: 'diff' },
  { names: ['application/xml-dtd'], extension: 'dtd' },
  { names: ['text/x-dylan'], extension: 'dylan' },
  { names: ['text/x-ecl'], extension: 'ecl' },
  { names: ['application/edn'], extension: 'edn' },
  { names: ['text/x-eiffel'], extension: 'e' },
  { names: ['text/x-elm'], extension: 'elm' },
  { names: ['application/x-ejs'], extension: 'ejs' },
  { names: ['application/x-erb'], extension: 'erb' },
  { names: ['text/x-erlang'], extension: 'erl' },
  { names: ['text/x-factor'], extension: 'factor' },
  { names: ['text/x-forth'], extension: 'forth' },
  { names: ['text/x-fortran'], extension: 'f' },
  { names: ['text/x-fsharp'], extension: 'fs' },
  { names: ['text/x-gas'], extension: 's' },
  { names: ['text/x-feature'], extension: 'feature' },
  { names: ['text/x-go'], extension: 'go' },
  { names: ['text/x-groovy'], extension: 'groovy' },
  { names: ['text/x-haml'], extension: 'haml' },
  { names: ['text/x-haskell'], extension: 'hs' },
  { names: ['text/x-literate-haskell'], extension: 'lhs' },
  { names: ['text/x-haxe'], extension: 'hx' },
  { names: ['text/x-hxml'], extension: 'hxml' },
  { names: ['application/x-aspx'], extension: 'aspx' },
  { names: ['text/html'], extension: 'html' },
  { names: ['text/x-idl'], extension: 'pro' },
  { names: ['text/x-pug'], extension: 'jade' },
  { names: ['text/x-java'], extension: 'java' },
  { names: ['application/x-jsp'], extension: 'jsp' },
  { names: ['text/javascript', 'text/ecmascript', 'application/javascript', 'application/x-javascript', 'application/ecmascript'], extension: 'js' },
  { names: ['application/json', 'application/x-json'], extension: 'json' },
  { names: ['application/ld+json'], extension: 'jsonld' },
  { names: ['text/jsx'], extension: 'jsx' },
  { names: ['text/jinja2'], extension: 'j2' },
  { names: ['text/x-julia'], extension: 'jl' },
  { names: ['text/x-kotlin'], extension: 'kt' },
  { names: ['text/x-less'], extension: 'less' },
  { names: ['text/x-livescript'], extension: 'ls' },
  { names: ['text/x-lua'], extension: 'lua' },
  { names: ['text/x-markdown'], extension: 'md' },
  { names: ['text/x-mariadb'], extension: 'sql' },
  { names: ['text/x-mathematica'], extension: 'm' },
  { names: ['text/x-modelica'], extension: 'mo' },
  { names: ['text/x-mumps'], extension: 'mps' },
  { names: ['text/x-mssql'], extension: 'sql' },
  { names: ['application/mbox'], extension: 'mbox' },
  { names: ['text/x-mysql'], extension: 'sql' },
  { names: ['text/x-nsis'], extension: 'nsh' },
  { names: ['application/n-triples', 'application/n-quads', 'text/n-triples'], extension: 'nt' },
  { names: ['text/x-objectivec'], extension: 'm' },
  { names: ['text/x-objectivec++'], extension: 'mm' },
  { names: ['text/x-ocaml'], extension: 'ml' },
  { names: ['text/x-octave'], extension: 'm' },
  { names: ['text/x-oz'], extension: 'oz' },
  { names: ['text/x-pascal'], extension: 'p' },
  { names: ['null'], extension: 'jsonld' },
  { names: ['text/x-perl'], extension: 'pl' },
  { names: ['text/x-php', 'application/x-httpd-php', 'application/x-httpd-php-open'], extension: 'php'},
  { names: ['text/x-pig'], extension: 'pig' },
  { names: ['text/plain'], extension: 'txt' },
  { names: ['text/x-plsql'], extension: 'pls' },
  { names: ['text/x-pgsql'], extension: 'sql' },
  { names: ['application/x-powershell'], extension: 'ps1' },
  { names: ['text/x-properties'], extension: 'properties' },
  { names: ['text/x-protobuf'], extension: 'proto' },
  { names: ['text/x-python'], extension: 'BUILD' },
  { names: ['text/x-puppet'], extension: 'pp' },
  { names: ['text/x-q'], extension: 'q' },
  { names: ['text/x-rsrc'], extension: 'r' },
  { names: ['text/x-rst'], extension: 'rst' },
  { names: ['text/x-rpm-spec'], extension: 'spec' },
  { names: ['text/x-ruby'], extension: 'rb' },
  { names: ['text/x-rustsrc'], extension: 'rs' },
  { names: ['text/x-sas'], extension: 'sas' },
  { names: ['text/x-sass'], extension: 'sass' },
  { names: ['text/x-scala'], extension: 'scala' },
  { names: ['text/x-scheme'], extension: 'scm' },
  { names: ['text/x-scss'], extension: 'scss' },
  { names: ['text/x-sh', 'application/x-sh'], extension: 'sh' },
  { names: ['application/sieve'], extension: 'siv' },
  { names: ['text/x-slim', 'application/x-slim'], extension: 'slim' },
  { names: ['text/x-stsrc'], extension: 'st' },
  { names: ['text/x-smarty'], extension: 'tpl' },
  { names: ['text/x-sml'], extension: 'sml' },
  { names: ['text/x-soy'], extension: 'soy' },
  { names: ['application/sparql-query'], extension: 'rq' },
  { names: ['text/x-sql'], extension: 'sql' },
  { names: ['text/x-sqlite'], extension: 'sqlite' },
  { names: ['text/x-squirrel'], extension: 'nut' },
  { names: ['text/x-styl'], extension: 'styl' },
  { names: ['text/x-swift'], extension: 'swift' },
  { names: ['text/x-latex'], extension: 'text' },
  { names: ['text/x-systemverilog'], extension: 'v' },
  { names: ['text/x-tcl'], extension: 'tcl' },
  { names: ['text/x-textile'], extension: 'textile' },
  { names: ['text/x-toml'], extension: 'toml' },
  { names: ['text/x-ttcn'], extension: 'ttcn' },
  { names: ['text/x-ttcn-cfg'], extension: 'cfg' },
  { names: ['text/turtle'], extension: 'ttl' },
  { names: ['application/typescript'], extension: 'ts' },
  { names: ['text/typescript-jsx'], extension: 'tsx' },
  { names: ['text/x-webidl'], extension: 'webidl' },
  { names: ['text/x-vb'], extension: 'vb' },
  { names: ['text/vbscript'], extension: 'vbs' },
  { names: ['text/velocity'], extension: 'vtl' },
  { names: ['text/x-verilog'], extension: 'v' },
  { names: ['text/x-vhdl'], extension: 'vhd' },
  { names: ['script/x-vue', 'text/x-vue'], extension: 'vue' },
  { names: ['application/xml', 'text/xml'], extension: 'xml' },
  { names: ['application/xquery'], extension: 'xy' },
  { names: ['text/x-yacas'], extension: 'ys' },
  { names: ['text/x-yaml', 'text/yaml'], extension: 'yaml' },
  { names: ['text/x-z80'], extension: 'z80' },
  { names: ['text/x-mscgen'], extension: 'mscgen' },
  { names: ['text/x-xu'], extension: 'xu' },
  { names: ['text/x-msgenny'], extension: 'msgenny' },
];
